equinor/spinedatasheetweb

- src/Components/BackButton.tsx
- src/Views/JIP33TabView.tsx
- src/pages/EquipmentListPage.tsx
Added back button component and added to equipment list page and jip33 page
> feat: Added back button to pages

- src/Components/BackButton.tsx
Added button component instead of just icon in back button component to have a hover color
> fix: Added color when hovering over back button

- src/Components/ReviewCommentsSideSheet.tsx
- src/Views/JIP33InstrumentTabView.tsx
[AB#114700](https://dev.azure.com/EquinorASA/bb9bd8cb-74f7-4ffa-b0cb-60eff0a0be58/_workitems/edit/114700)
> feat: add comment sidesheet for tag

- src/config.ts
[AB#114569](https://dev.azure.com/EquinorASA/bb9bd8cb-74f7-4ffa-b0cb-60eff0a0be58/_workitems/edit/114569)
> fix: Added setContextFilter to only show SFP project in context selector

- src/Components/EquipmentListTable.tsx
- src/Views/EquipmentListView.tsx
[AB#114423](https://dev.azure.com/EquinorASA/bb9bd8cb-74f7-4ffa-b0cb-60eff0a0be58/_workitems/edit/114423)
[AB#115470](https://dev.azure.com/EquinorASA/bb9bd8cb-74f7-4ffa-b0cb-60eff0a0be58/_workitems/edit/115470)
> fix: use location in tag link

- src/Components/SideSheet/Area/AreaSideSheet.tsx
- src/Components/SideSheet/ChangeLog/ChangeLogSideSheet.tsx
- src/Components/SideSheet/SheetContainer.tsx
- src/Components/SideSheet/Table.tsx
[AB#120199](https://dev.azure.com/EquinorASA/bb9bd8cb-74f7-4ffa-b0cb-60eff0a0be58/_workitems/edit/120199)
> feat: changelog sheet added

- src/Components/EquipmentListView/EquipmentListReview.tsx
- src/Components/JIP33Table/JIP33Table.tsx
- src/api/CommentService.ts
- src/api/ProjectService.ts
[AB#120727](https://dev.azure.com/EquinorASA/bb9bd8cb-74f7-4ffa-b0cb-60eff0a0be58/_workitems/edit/120727)
> fix: Add review function to tag view

- package.json
- src/Components/JIP33Table/JIP33Table.tsx
- yarn.lock
[AB#121826](https://dev.azure.com/EquinorASA/bb9bd8cb-74f7-4ffa-b0cb-60eff0a0be58/_workitems/edit/121826)
> feat: Upgrade fusion ag-grid module to version 30

- src/Components/SideSheet/Comments/Components/CommentView.tsx
- src/Components/SideSheet/Comments/Components/DialogueBox.tsx
- src/Components/SideSheet/Comments/Components/InputController.tsx
- src/Components/SideSheet/Comments/Components/RenderComment.tsx
- src/Views/JIP33ElectricalTabView.tsx
- src/Views/JIP33InstrumentTabView.tsx
- src/Views/JIP33MechanicalTabView.tsx
- src/Views/TagComparisonView.tsx
- src/utils/helpers.tsx
- fix: collapsed tag comparison table
- feat: color coded and separated chat
> tag compare

- src/Components/SideSheet/Comments/CommentSideSheet.tsx
- src/Components/SideSheet/Comments/Components/CommentView.tsx
- src/Components/SideSheet/SheetContainer.tsx
- src/Components/TagComparisonTable/ColumnDefs/EquipmentConditionColumnDefs.tsx
- src/Components/TagComparisonTable/ColumnDefs/GeneralColumnDefs.tsx
- src/Components/TagComparisonTable/ColumnDefs/TR3111ColumnDefs.tsx
- src/Components/TagComparisonTable/ColumnDefs/TagsColumnDefs..tsx
- src/Views/JIP33InstrumentTabView.tsx
- src/utils/helpers.tsx
- feat: auto scroll to newest comments
- feat: jsdoc & helpers refactor
- feat: auto scroll to top of sidesheet
> grouped conversations

- src/Components/SideSheet/Comments/Components/ClusteredMessages.tsx
[AB#124207](https://dev.azure.com/EquinorASA/bb9bd8cb-74f7-4ffa-b0cb-60eff0a0be58/_workitems/edit/124207)
> feat: Show "edited" with timestamp for edited messages

- src/Components/TagComparisonTable/ColumnDefs/OperatingConditionsColumnDefs.tsx
- src/Components/TagComparisonTable/TagComparisonTable.tsx
- src/Models/InstrumentPurchaserRequirement.ts
- src/Models/InstrumentSupplierOfferedProduct.ts
- src/types.d.ts
[AB#125042](https://dev.azure.com/EquinorASA/bb9bd8cb-74f7-4ffa-b0cb-60eff0a0be58/_workitems/edit/125042)
> feat: Add Operating conditions to tag comparison view

- src/Components/JIP33Table/TR3111GeneralRowData.tsx
- src/Views/JIP33InstrumentTabView.tsx
> feat: Add TR3111 properties to general tabs in NORSOK and JIP33

- src/Components/NORSOKTable/RowData/GeneralRowData.tsx
- src/Components/TagComparisonTable/ColumnDefs/TR3111ColumnDefs.tsx
- src/Models/TagData.ts
- src/types.d.ts
> feat: Add more TR3111 properties to tag comparison view

- src/Components/JIP33Table/JIP33Table.tsx
- src/Components/TagComparisonTable/ColumnDefs/OperatingConditionsColumnDefs.tsx
- src/Components/TagComparisonTable/TagComparisonTable.tsx
> fix: Remove cell type from ag grid tables

- src/Components/SideSheet/Comments/Components/ClusteredMessages.tsx
> fix: Fixed comment bubble cluster width

- src/Components/SideSheet/SheetContainer.tsx
> feat: Use escape key to close sidesheet

- src/Components/TagComparisonTable/TagComparisonTable.tsx
> feat: Make sidebar filter non-expandable

- src/Components/JIP33Table/JIP33Table.tsx
- src/Components/JIP33WithSideMenu.tsx
- src/Components/SideSheet/Components/SheetContainer.tsx
- src/Components/SideSheet/TagPropertySideSheet.tsx
- src/Components/SideSheet/TagSideSheet.tsx
- src/Components/TagComparisonTable/TagComparisonTable.tsx
- fix: sidesheet not opening
- fixed for real this time
> fix: sidesheet does not open using button

- src/Components/Charts/TotalReviewStatus.tsx
- src/Components/Charts/TotalTagRequirement.tsx
- src/Components/EquipmentListView/EquipmentListReview.tsx
- src/Components/Header/StackedBar.tsx
- src/Components/JIP33Table/JIP33Table.tsx
- src/Components/JIP33WithSideMenu.tsx
- src/Components/SideSheet/Activity/ActivitySideSheet.tsx
- src/Components/SideSheet/Comments/CommentSideSheet.tsx
- src/Components/SideSheet/Comments/Components/CommentView.tsx
- src/Components/SideSheet/Comments/Components/ConversationCard.tsx
- src/Components/SideSheet/Comments/Components/InputController.tsx
- src/Components/SideSheet/Comments/Components/InputField.tsx
- src/Components/SideSheet/Components/SheetContainer.tsx
- src/Components/SideSheet/Equipment/EquipmentSideSheet.tsx
- src/Components/SideSheet/Equipment/Tabs/Media.tsx
- src/Components/SideSheet/TagPropertySideSheet.tsx
- src/Components/SideSheet/TagSideSheet.tsx
- src/Components/TagComparisonTable/TagComparisonTable.tsx
- src/Components/Toast/ToastCard.tsx
- src/Context/ViewContext.tsx
- src/Views/EquipmentListView.tsx
- src/Views/JIP33ElectricalTabView.tsx
- src/Views/JIP33InstrumentTabView.tsx
- src/Views/JIP33MechanicalTabView.tsx
- src/Views/TagComparisonView.tsx
- src/utils/helpers.tsx
- feat: added documentation & improved conversation view
- feat: presistent sidesheet
- cleanup
> latestMessageShown

- package.json
- src/Components/SideSheet/Comments/Components/CommentView.tsx
- src/Components/SideSheet/Comments/Components/ConversationCard.tsx
- src/Components/SideSheet/Comments/Components/InputField.tsx
- src/Components/SideSheet/Comments/Components/RenderComment.tsx
- src/utils/helpers.tsx
- yarn.lock
- fix: add dompurify (#163)
- fix: Personphoto (#164)
- fix: first message not displaying edited (#166)
- feat: Add hardcoded dummydata to datasheet sidesheet
- feat: overhauled conversation view & cleanup
- feat: improved sanitation
> sanitation

- src/Components/SideSheet/Comments/Components/ClusteredMessages.tsx
- src/Components/SideSheet/Comments/Components/MessageBox.tsx
- src/Components/TagComparisonTable/TagComparisonTable.tsx
- src/Views/EquipmentListView.tsx
- src/Views/NavigatorHeader.tsx
- fix: UI not loading without refresh on initial project select
- fix: mishandled activeTagData causes visible sideheetopen on load sometimes
> containerView2

- src/AppRouter.tsx
- src/Components/Containers/Components/DraggableConversationCard.tsx
- src/Components/Containers/DraggableCardTable.tsx
- src/Components/EquipmentListView/EquipmentListTable.tsx
- src/Views/ContainerPicker.tsx
- src/Views/ContainerView.tsx
- fix: status circle unknown in conversation cards (container view)
- feat: container table & correctly linked child routes
> containerOverview

- src/Components/Buttons/ReviewButton.tsx
- src/Components/Containers/ContainerTable.tsx
- src/Components/Containers/DraggableCardTable.tsx
- src/Views/ContainerPicker.tsx
- src/Views/ContainerView.tsx
- src/Views/EquipmentListView.tsx
- src/api/ConversationService.ts
- src/types.d.ts
- Show correct container state
- Update the active container reviewer
- Update backend when dragging conversation cards to different state
> fix: Fix setting state when updating container reviewer
